# Generated by Django 4.2.7 on 2025-06-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='trade_type',
        ),
        migrations.AlterField(
            model_name='trade',
            name='position_type',
            field=models.CharField(choices=[('LONG', 'Long (Buy - expecting price to rise)'), ('SHORT', 'Short (Sell - expecting price to fall)')], default='LONG', help_text='Long = Buy expecting price up, Short = Sell expecting price down', max_length=5),
        ),
    ]
