# Generated by Django 4.2.7 on 2025-06-26 05:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_trade_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='position_size',
            field=models.DecimalField(decimal_places=4, help_text='Number of shares/units traded (minimum 0.01)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
