# Generated by Django 4.2.7 on 2025-06-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_trade_position_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='asset_type',
            field=models.CharField(choices=[('FOREX', 'Forex'), ('COMMODITY', 'Commodity'), ('OIL', 'Oil'), ('STOCK', 'Stock')], default='FOREX', help_text='Type of asset being traded', max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='position_type',
            field=models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', help_text='Long = Buy expecting price up, Short = Sell expecting price down', max_length=5),
        ),
    ]
