# Generated by Django 4.2.7 on 2025-06-26 06:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_trade_asset_type_alter_trade_position_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='asset_type',
            field=models.CharField(choices=[('FOREX', 'Forex'), ('STOCK', 'Stock/ETF'), ('COMMODITY', 'Commodity'), ('OIL', 'Oil'), ('CRYPTO', 'Cryptocurrency')], default='FOREX', help_text='Type of asset being traded', max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='position_size',
            field=models.DecimalField(decimal_places=4, help_text='Number of units/shares traded (not lots). For Forex: actual units, for Stocks: number of shares, etc.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
