# Generated by Django 4.2.7 on 2025-06-26 10:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_trade_asset_type_alter_trade_position_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='exit_reason',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual Close'), ('TAKE_PROFIT', 'Take Profit Hit'), ('STOP_LOSS', 'Stop Loss Hit')], help_text='How the trade was closed', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='position_size',
            field=models.DecimalField(decimal_places=4, help_text='Number of units/shares traded (not lots). Examples: Forex: 10,000-100,000 units, Stocks: 100+ shares, Gold: 1-100 oz', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
